../upd_one_param_all_runs.sh Dt 0.05
../upd_one_param_all_runs.sh bigDt 10.0
../upd_one_param_all_runs.sh bakSteps 1000
../upd_one_param_all_runs.sh DQtensCalc 1
../upd_one_param_all_runs.sh DQtensSteps 1
../upd_one_param_all_runs.sh PtensCalc 1
../upd_one_param_all_runs.sh PtensSteps 1
../upd_one_param_all_runs.sh VSteps 1000
../upd_one_param_all_runs.sh scalevel 0
